projekt_id          = "vollrad-werkverzeichnis"
kuenstler           = "kutscher"
github_verbindung   = "Werkverzeichnis"
github_repo         = "allen-ziegenfus/allen-ziegenfus.github.io"
branch              = "firestore-build"
seiten_url          = "https://firestore-build.werkverzeichnis-c25.pages.dev"
pages_projekt       = "werkverzeichnis"
cloudflare_konto_id = "cf3fa9a06c8f2e93e24fa3eeaa80b783"
