name: Publish website
on: [push, workflow_dispatch]
jobs:
  Publish-Site:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - run: yarn install
      - run: yarn build
        env:
          BASE_ID: ${{ secrets.BASE_ID }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          TABLE_ID: ${{ secrets.TABLE_ID }}
          VIEW: ${{ secrets.VIEW }}
          HOMEPAGE_FIELD_ORDER: ${{ secrets.HOMEPAGE_FIELD_ORDER }}
          FIELD_ORDER: ${{ secrets.FIELD_ORDER }}
          HEADER_TITLE: ${{ secrets.HEADER_TITLE }}
          PAGE_TITLE_COLUMN: ${{ secrets.PAGE_TITLE_COLUMN }}
          SITE_TITLE: ${{ secrets.SITE_TITLE }}
          MARKDOWN_FIELDS: ${{ secrets.MARKDOWN_FIELDS }}
          TITLE_FIELD: ${{ secrets.TITLE_FIELD }}
          IMAGE_FIELD: ${{ secrets.IMAGE_FIELD }}
          SITE_PREFIX: ${{ secrets.SITE_PREFIX }}
          ROWS_PER_PAGE: ${{ secrets.ROWS_PER_PAGE }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          cp -r dist /tmp
          git checkout master
          git clean -fdx
          cp -r /tmp/dist/* .
          git add -A 
          git commit -m "Build of github site"
          git push
